from rest_framework import serializers

from .models import Research, ResearchSource


# =============================================================
# RESEARCH SOURCE SERIALIZER
# =============================================================

class ResearchSourceSerializer(serializers.ModelSerializer):

    class Meta:
        model = ResearchSource

        fields = [
            "id",
            "title",
            "url",
            "snippet",
            "created_at",
        ]

        read_only_fields = [
            "id",
            "created_at",
        ]


# =============================================================
# RESEARCH SERIALIZER
# =============================================================

class ResearchSerializer(serializers.ModelSerializer):

    # Include all sources belonging to this research.
    sources = ResearchSourceSerializer(
        many=True,
        read_only=True
    )

    class Meta:
        model = Research

        fields = [
            "id",
            "question",
            "status",
            "final_report",

            # AI-generated summary
            "summary",

            # AI Critic result
            "critic_status",
            "critic_feedback",

            # Research sources
            "sources",

            "created_at",
            "updated_at",
        ]

        read_only_fields = [
            "id",
            "status",
            "final_report",

            # Generated by the AI workflow
            "summary",
            "critic_status",
            "critic_feedback",

            "sources",
            "created_at",
            "updated_at",
        ]