# Generated by Django 6.1.1 on 2026-09-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching'), ('reading', 'Reading'), ('writing', 'Writing'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
