# Generated by Django 6.1.1 on 2026-09-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_research_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='critic_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='research',
            name='final_report',
            field=models.TextField(blank=True, default=''),
        ),
    ]
