# Generated by Django 6.1.1 on 2026-09-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_research_critic_feedback_research_final_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('url', models.URLField(max_length=2000)),
                ('snippet', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.research')),
            ],
        ),
    ]
