# Generated by Django 6.1.1 on 2026-09-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_researchsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='critic_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
