# Generated by Django 6.1.1 on 2026-09-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_research_critic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
