# ---------------------------------------------------------
# SUMMARY AGENT
# ---------------------------------------------------------
# This agent generates a short summary from the final
# research report.
#
# Flow:
#
# Final Report
#      ↓
# Summary Agent
#      ↓
# Short Summary
#      ↓
# PostgreSQL
# ---------------------------------------------------------


# ---------------------------------------------------------
# IMPORTS
# ---------------------------------------------------------

from langchain_groq import ChatGroq
from dotenv import load_dotenv


# ---------------------------------------------------------
# LOAD ENVIRONMENT VARIABLES
# ---------------------------------------------------------

load_dotenv()


# ---------------------------------------------------------
# LLM CONFIGURATION
# ---------------------------------------------------------

llm = ChatGroq(
    model="qwen/qwen3.8-27b",
    temperature=0,
    max_tokens=300,
    reasoning_effort="none"
)


# ---------------------------------------------------------
# SUMMARY FUNCTION
# ---------------------------------------------------------

def run_summary_agent(final_report):
    """
    Generate a concise summary of the final research report.

    Parameters:
        final_report:
            The final report generated by the Writer Agent.

    Returns:
        A short summary as plain text.
    """

    # -----------------------------------------------------
    # PROMPT
    # -----------------------------------------------------

    prompt = f"""
You are a research summary writer.

Create a concise summary of the research report below.

FINAL RESEARCH REPORT:
{final_report}

Rules:

- Summarize only information present in the report.
- Do not add new facts.
- Do not invent information.
- Focus on the most important findings.
- Keep the summary between 80 and 120 words.
- Use clear professional language.
- Return ONLY the summary.
"""

    # -----------------------------------------------------
    # CALL LLM
    # -----------------------------------------------------

    response = llm.invoke(prompt)

    # -----------------------------------------------------
    # CLEAN RESULT
    # -----------------------------------------------------

    summary = response.content.strip()

    return summary